# plugin-descriptor.properties

name=License Validator
description=A plugin that validates OpenSearch licenses
version=1.0.0
opensearch.version=2.19.1
classname=com.supra.plugins.LicenseValidatorPlugin
has.native.controller=false
java.version=17
